# Config defaults per training SWIN con MIM
# Modifica i valori qui o passa un file differente via --config

data_path: '/home/jovyan/nfs/datasets/ILSVRC2012'
batch_size: 64
epochs: 300
model: 'swin_base_patch4_window7_224_8k_vocab'
mask_patches: null
d_vae_path: './dalee_weight'
d_vae_type: 'dall-e' #customized
output_dir: '/home/jovyan/nfs/lsgroi/outputs/swin_mim'
device: 'cuda'
seed: 0
mask_patches: 75
num_workers: 10
input_size: 224
second_input_size: 448
trial: 0
